# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E4AlfbMorVnvbA-jpRxrJX2Fw0uhgnbW
"""

import pandas as pd

# Load dataset (skip metadata rows)
df = pd.read_csv("/content/API_SP.POP.TOTL_DS2_en_csv_v2_13582.csv", skiprows=4)

# Display first 5 rows
print(df.head())

# Rename columns
df.rename(columns={"Country Name": "Country", "2023": "Population_2023"}, inplace=True)

df

# Remove non-country entries
excluded_terms = ["World", "income", "IBRD", "IDA", "demographic", "total", "Pacific"]
df_countries = df[~df['Country'].str.contains('|'.join(excluded_terms), case=False, na=False)]

# Sort by population and select the top 10 countries
df_top10 = df_countries[['Country', 'Population_2023']].dropna().sort_values(by='Population_2023', ascending=False).head(10)

# Display the top 10 populated countries
df_top10

import matplotlib.pyplot as plt

# Plot the data
plt.figure(figsize=(10, 5))
plt.bar(df_top10['Country'], df_top10['Population_2023'], color='skyblue')

# Labels & Title
plt.xlabel("Country")
plt.ylabel("Population (2023)")
plt.title("Top 10 Most Populated Countries (2023)")
plt.xticks(rotation=45)

# Show the plot
plt.show()